name: 🛠️ Frontend CI for Static HTML/CSS

on:
  push:
    branches:
      - ZIG-19-react-frontend-login-home
      - ZIG-20-react-menu-cart-checkout
      - ZIG-21-frontend-backend-connect
      - ZIG-22-dockerize-react-frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: ✅ Run Basic Lint/Check
        run: |
          echo "No build steps defined for static HTML/CSS"
          echo "You can add custom scripts here if needed"
